# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('register_date', models.DateField()),
                ('work_name', models.CharField(max_length=30)),
                ('work_pay', models.FloatField(default=10.0)),
                ('time', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['nickname'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
