# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170926_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(default=10000000),
        ),
    ]
