# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170927_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
    ]
