# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170927_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_record',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='time_record',
            name='start_time',
        ),
        migrations.AddField(
            model_name='time_record',
            name='type',
            field=models.CharField(default='开始时间', max_length=10),
        ),
    ]
